#pragma once
#include <pebble.h>

enum HandShape { DAUPHINE, BAGUETTE, PENCIL, BREGUET, SWISSRAIL };

#define DAUPINE_HOUR_THICKNESS 8
#define DAUPINE_MINUTE_THICKNESS 6
static const GPathInfo DAUPHINE_HOUR_POINTS = {
	4, (GPoint []){
		{0, DAUPINE_HOUR_THICKNESS},
		{-DAUPINE_HOUR_THICKNESS, 0},
		{0, -46},
		{DAUPINE_HOUR_THICKNESS, 0}
	}
};
static const GPathInfo DAUPHINE_MINUTE_POINTS = {
	4, (GPoint []){
		{0, DAUPINE_MINUTE_THICKNESS},
		{-DAUPINE_MINUTE_THICKNESS, 0},
		{0, -80},
		{DAUPINE_MINUTE_THICKNESS, 0}
	}
};

#define BAGUETTE_THICKNESS 7
#define BAGUETTE_HOUR_LENGTH 46
#define BAGUETTE_MINUTE_LENGTH 70

#define PENCIL_SHARPNESS 4.2
#define PENCIL_THICKNESS 5
#define PENCIL_HOUR_LENGTH 40
#define PENCIL_MINUTE_LENGTH 65
#define PENCIL_AXLE_RADIUS 6

#define BREGUET_THICKNESS 5
#define BREGUET_HOUR_LENGTH 50
#define BREGUET_MINUTE_LENGTH 85
#define BREGUET_HOUR_RADIUS 7
#define BREGUET_MINUTE_RADIUS 6
#define BREGUET_EYE_THICKNESS 3
#define BREGUET_AXLE_RADIUS 5
#define BREGUET_HOUR_EYE_DIST 31
#define BREGUET_MINUTE_EYE_DIST 65

#define SWISSRAIL_THICKNESS 3
#define SWISSRAIL_HOUR_RADIUS 7
#define SWISSRAIL_MINUTE_RADIUS 6
#define SWISSRAIL_AXLE_RADIUS 3
#if defined(PBL_ROUND)
#define SWISSRAIL_HOUR_LENGTH 37
#define SWISSRAIL_MINUTE_LENGTH 70
#define SWISSRAIL_HOUR_EXTENDER_LENGTH 18
#define SWISSRAIL_MINUTE_EXTENDER_LENGTH 20
#elif defined(PBL_RECT)
#define SWISSRAIL_HOUR_LENGTH 35
#define SWISSRAIL_MINUTE_LENGTH 66
#define SWISSRAIL_HOUR_EXTENDER_LENGTH 16
#define SWISSRAIL_MINUTE_EXTENDER_LENGTH 18
#endif
